# Generated by Django 2.2.10 on 2020-02-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herotype',
            old_name='ability',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='herotype',
            old_name='type',
            new_name='speciality',
        ),
    ]
