# Generated by Django 2.2.10 on 2020-02-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_auto_20200227_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herotype',
            old_name='speciality',
            new_name='specialty',
        ),
    ]
